{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valkey-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  selector:
    {{- include "valkey-operator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
